### ISSUE TITLE
Update settings API to fetch dynamically

### ISSUE THREAD

**Issue by rgantzos** [STForScratch/ScratchTools#186]
Rather than having the settings update every page load, switch over the API so that it fetches the storage from the background files. This makes it so that changes update on the page immediately, without having to reload.

**Comment by ellieya** [comment]
Can I try tackling this?

**Comment by rgantzosonscratch** [comment]
> Can I try tackling this?

Absolutely!

**Comment by techrajdeep** [comment]
I am looking for an issue for my first contribution . Can you help me here. Can I take on this .

**Comment by rgantzosonscratch** [comment]
> I am looking for an issue for my first contribution . Can you help me here. Can I take on this .

Feel free to take this on! If you understand manifest v3 for browser extensions, then this seems perfect. [This code](https://github.com/STForScratch/ScratchTools/blob/e93ef374a974f2c5cfc6d3cdcc7e64ac70a82dd7/extras/background.js#L119-L138) injects the option data. That just needs to be injected into the tabs whenever the options change.

**Comment by techrajdeep** [comment]
@rgantzosonscratch , Could you please assign it to me
