### ISSUE TITLE
Add video or gif with the usage of the library to README

### ISSUE THREAD

**Issue by jcubic** [STForScratch/ScratchTools#194]
**Please describe your idea.**
Add video or gif with the usage of the library to README

**Describe how the idea would be helpful**
It helps when someone can see some visuals instead of just text. To see what to project look like you need to install the extension. I don't think that people that just checking will install extensions to see what this is all about.

**Additional context**
I would just test the most important features and record gifs, all OSes have a tool to record a screencast in form of a gif. Here is an example of one of my projects [jcubic/sysend.js](https://github.com/jcubic/sysend.js), if you can't easily share a link to the demo, a gif is the second best thing.

**Comment by rgantzosonscratch** [comment]
Just videos for the README in general or for something specific?

**Comment by jcubic** [comment]
This is your project, you should know how to showcase your project. Right now you don't have anything to show people.

**Comment by rgantzosonscratch** [comment]
Alright thanks!

**Comment by mistysloth** [comment]
Closed issue as the pr has been merged.
