### ISSUE TITLE
Workflow failing SPAM

### ISSUE THREAD

**Issue by jcubic** [STForScratch/ScratchTools#195]
**Describe the bug**
You have an error in your workflow, Just got 2 emails with spam from this repo.

**Additional context**
I think that it suppose to greet people but it SPAM people with the GitHub failed job instead. It doesn't look good.

**Comment by jcubic** [comment]
Ref: https://github.com/STForScratch/ScratchTools/actions/runs/3152486252

**Comment by rgantzosonscratch** [comment]
Fixed.
