### ISSUE TITLE
Responsive issue on https://scratchtools.app/

### ISSUE THREAD

**Issue by ManavMalhotra** [STForScratch/ScratchTools#202]
**Describe the bug**
there is a responsiveness issue on the scratch website on the mobile screen.

1. On the https://scratchtools.app/ in the #Our Features section 
2. On the https://scratchtools.app/docs/ the code in the Adding the info section is getting out of the page

**Browser**
I was using chrome on my android device when I faced this issue.
I cross check the issue on Microsoft edge using dev tools 

![image](https://user-images.githubusercontent.com/64147782/193417601-09253878-03dd-4632-8e42-974f92eec8e3.png)

**Comment by rgantzosonscratch** [comment]
Fixed!
