### ISSUE TITLE
when it comes to a website frontend the logo adds a lot of value for good looks of website but here the logo is not visible.

### ISSUE THREAD

**Issue by Z3RO-O** [STForScratch/ScratchTools#207]
**Describe the bug**
The logo is not visible.

**Browser**
Chrome, Brave

Please assign this issue to me.

**Comment by rgantzosonscratch** [comment]
Where is the logo not visible?

**Comment by Z3RO-O** [comment]
On website

**Comment by rgantzosonscratch** [comment]
The logo does show on the website in all browsers, you might want to check if an adblocker is hiding it.

**Comment by Z3RO-O** [comment]
Thanks, I'll check it out.
