### ISSUE TITLE
Improvement of HomePage UI

### ISSUE THREAD

**Issue by BabyElias** [STForScratch/ScratchTools#208]
**Please describe your idea.**
Improving text alignment , color and highlight for headings & content on the HomePage and also, revamp the footer to make it distinctive from the rest of the website.

**Describe how the idea would be helpful**
Presently,there is no clear distinction between the headings, the content and the links, which decreases readability and visual appeal of the website. Revamping them will make it easier to attract first time users.

**Additional context**
![image](https://user-images.githubusercontent.com/95405559/193496810-31fe02f4-d0dc-459c-9b34-8f2f23cd816e.png)
For eg : The content within the topic here, is not even clearly visible due to it's greyish glare.

**Comment by BabyElias** [comment]
If possible, I would like to work on this issue under Hacktoberfest.

**Comment by rgantzosonscratch** [comment]
> If possible, I would like to work on this issue under Hacktoberfest.

Unfortunately, the website is closed-source. If you'd like, I can find a way to let you edit it.

**Comment by rgantzosonscratch** [comment]
Do you have a mockup?
