### ISSUE TITLE
Broken Images on Features Page

### ISSUE THREAD

**Issue by BabyElias** [STForScratch/ScratchTools#209]
**Describe the bug**
Some features have broken image icons.

**Screenshots**
![image](https://user-images.githubusercontent.com/95405559/193497020-42ad2394-4b23-49e0-b671-03f5227d934e.png)

**Comment by rgantzosonscratch** [comment]
This is because the image do not exist yet. We usually upload them within a few days, but we will possibly work on a fix in the future.
