### ISSUE TITLE
Not responsive 

### ISSUE THREAD

**Issue by AnkitaMalik22** [STForScratch/ScratchTools#214]
![Screenshot_20221005-200253.png](https://user-images.githubusercontent.com/80139836/194087282-1be64f7f-8399-4db5-9242-696c9b637622.png)

I would love to work on this issue. Please add hackoctoberfest label and assign me.

**Comment by rgantzosonscratch** [comment]
This repository is for the browser extension. The website, as said above, is closed source. We already know about this issue and we're working on it.
