### ISSUE TITLE
Sidebar balnk when signed out

### ISSUE THREAD

**Issue by Samq64** [STForScratch/ScratchTools#288]
**Describe the bug**
When signed out of Scratch the side bar is blank making it hard o navigate or sign in.

**Browser**
Chromium 108

**Screenshots**
![image](https://cdn.discordapp.com/attachments/995828149973700688/1053675703217954906/image.png)
![image](https://user-images.githubusercontent.com/81489795/208246698-c93c53da-0f24-4372-9771-7894901cee8e.png)

**Additional context**
The sidebar also makes it pretty much impossible to sign out.

**Comment by rgantzos** [comment]
Interesting that there aren't any errors for the sidebar. I'll look into it, thanks.

**Comment by veloce-vasta** [comment]
@rgantzos try looking at the features that modify the navbar first, youll find the culprit faster
