### ISSUE TITLE
Excessive wasted space when settings page opened in new tab

### ISSUE THREAD

**Issue by GarboMuffin** [STForScratch/ScratchTools#300]
**Describe the bug**
See screenshot

**Browser**
Chromium on Linux

**Screenshots**
![image](https://user-images.githubusercontent.com/33787854/210684008-bc7cc1be-7d8b-4933-9e22-2134b44f6cc3.png)

*Note: I unsubscribed from this issue, so if you want a reply, make sure to @ me*

**Comment by GarboMuffin** [comment]
Also note that the list of tools lacks a scrollbar

**Comment by MaterArc** [comment]
Yeah what is up with that margin lol

**Comment by GarboMuffin** [comment]
Depending on the initial screen width, you can even get this:

![image](https://user-images.githubusercontent.com/33787854/210697456-97b96a3e-c32d-4c01-9c5d-43dc57539f59.png)

**Comment by GarboMuffin** [comment]
This issue was not resolved

![image](https://github.com/STForScratch/ScratchTools/assets/33787854/e2304e6b-28ba-4a1b-bfbb-baa6c01dba43)
![image](https://github.com/STForScratch/ScratchTools/assets/33787854/6742aebe-e3f1-4092-bdf7-9e0af6d924fd)
