### ISSUE TITLE
Settings page search is not good

### ISSUE THREAD

**Issue by GarboMuffin** [STForScratch/ScratchTools#301]
**Describe the bug**
The search feature is not very good at searching. Noncomprehensive list of examples:

 - Search for "opacity" -> the one tool that has "opacity" in its name does not appear at the top
 - Search for "font" -> "Custom Website Font" appears after "Message Count"

I also think that requiring someone to press enter before searching does not make sense in this context

**Browser**
Chromium on Linux

**Screenshots**
![image](https://user-images.githubusercontent.com/33787854/210684578-84faa79d-baaa-4a2b-a654-67cf3d0024b3.png)

*Note: I unsubscribed from this issue, so if you want a reply, make sure to @ me*

**Comment by MaterArc** [comment]
I agree with this though. Many times have I wanted to find a feature and the search bar did not help.

**Comment by rgantzos** [comment]
Yeah, I've noticed it is hard to find what you're looking for sometimes. I'm working on a complete redo of the settings page, since it's currently extremely complicated and really needs to be simplified.
