### ISSUE TITLE
Sidebar tool causes Scratch website to be almost unusable when signed out

### ISSUE THREAD

**Issue by GarboMuffin** [STForScratch/ScratchTools#302]
**Describe the bug**
When signed out, the "Sidebar" tool causes Scratch's menu bar to be broken. It is impossible to sign in or navigate any of the links that would normally be in the menu bar.

**Browser**
Chromium on Linux

**Screenshots**
![image](https://user-images.githubusercontent.com/33787854/210684828-c0b9c7f4-0651-485e-b4f4-2e81073b94fe.png)

**Comment by MaterArc** [comment]
This is a duplicate issue. I will close this one for now.
