### ISSUE TITLE
Opacity slider has numerous bugs

### ISSUE THREAD

**Issue by GarboMuffin** [STForScratch/ScratchTools#308]
**Describe the bug**

https://user-images.githubusercontent.com/33787854/210688016-edc4165f-d178-47bb-ba98-3203a5981d4d.mp4

Roughly in order of the video:

 - Sliders silently error on gradients
 - Dragging the sliders causes excessive lag
 - When the slider gets close to the left, but not necessarily all the way to the left, the color is replaced with black and going back up on the slider does not restore the original color
 - While undo/redo technically works, for some reason there is an intermediate step where some of the objects are flipped horizontally.
 - Additionally, every movement of the opacity slider seems to cause a new undo/redo entry, so undoing an opacity change is extremely slow and seems to very quickly fill up the undo/redo history

Not shown in video:

 - The sliders are initially at 50% for some reason, until someone interacts with the editor

**Browser**

Chromium on Linux

*Note: I unsubscribed from this issue, so if you want a reply, make sure to @ me*

**Comment by GarboMuffin** [comment]
It is also worth noting, although I happen to know these will be quite difficult to fix as a browser extension:

 - Bitmap brush tool does not support opacity
 - Bitmap rectangle tool in outline mode does not support opacity
 - Bitmap circle tool does not support opacity properly (and again, outlined mode not at all)

**Comment by rgantzos** [comment]
One thing we'll be doing is making it so ScratchTools can detect if Scratch Addons' opacity slider is enabled, and disable itself if it is.

**Comment by veloce-vasta** [comment]
> One thing we'll be doing is making it so ScratchTools can detect if Scratch Addons' opacity slider is enabled, and disable itself if it is.

Is there any way to overrule it? I think that this is way overdue because it says "Both are compatible for the most part though, so there's no downside to having both installed." We should try to fix this as quickly as possible

**Comment by rgantzos** [comment]
> > One thing we'll be doing is making it so ScratchTools can detect if Scratch Addons' opacity slider is enabled, and disable itself if it is.
> 
> Is there any way to overrule it? I think that this is way overdue because it says "Both are compatible for the most part though, so there's no downside to having both installed." We should try to fix this as quickly as possible

They're still compatible for the most part. We haven't yet made it so that we automatically disable our opacity slider if SA has their's enabled.
