### ISSUE TITLE
Follower count on projects shows nonsense in my stuff page

### ISSUE THREAD

**Issue by GarboMuffin** [STForScratch/ScratchTools#312]
**Describe the bug**

![image](https://user-images.githubusercontent.com/33787854/210691668-eefc9e14-9713-4e68-a718-1b2cca93fbf6.png)

It probably shouldn't be showing up on this page, this account has 0 followers, and the website design is broken

**Browser**
Chromium on Linux

*Note: I unsubscribed from this issue, so if you want a reply, make sure to @ me*

**Comment by rgantzos** [comment]
<img width="465" alt="Screenshot 2023-01-17 at 9 44 21 AM" src="https://user-images.githubusercontent.com/86856959/212973068-9e511122-79c5-41d7-9c9d-e0b9d8014c9b.png">
I'll fix this now, and it seems to be based on the account "Untitled-2", which does have 61 followers. Not the link itself.
