### ISSUE TITLE
Many unused JS files still live in the repository

### ISSUE THREAD

**Issue by GarboMuffin** [STForScratch/ScratchTools#317]
My understanding is that each feature needs to be listed in `features.json` and JS files that aren't listed here have no way of running. If that is the case, it appears these files are fully unused:

 - accurate-love-counts.js
 - color-slider-input.js
 - delete-custom-block-uses.js
 - fps.js
 - leopard.js
 - sprite-hover-data.js
 - turbowarp-button.js

Keeping these around is unnecessary and distracts from actual live code. If they need to be retrieved in the future, `git` is able to do this for you.

*Note: I unsubscribed from this issue, so if you want a reply, make sure to @ me*

**Comment by GarboMuffin** [comment]
Similarly I can't see where extras/stsettings.js is used

**Comment by veloce-vasta** [comment]
Idk if we should delete the files altogether or just include the features in the `features.json`?
