### ISSUE TITLE
Links in the settings page should be <a> elements with an href

### ISSUE THREAD

**Issue by GarboMuffin** [STForScratch/ScratchTools#324]
**Describe the bug**

For example, consider this link:

![image](https://user-images.githubusercontent.com/33787854/210700962-7fbe0a5e-0344-4d29-837f-02854075b2b4.png)

This should be:

```html
<a href="https://scratch.mit.edu/users/rgantzos/" target="_blank">rgantzos</a>
```

but instead it's an `<a>` with an `onclick`:

https://github.com/STForScratch/ScratchTools/blob/ae08fd6faa19035d3c0707bd30062adf0cb3e64a/extras/popup.js#L466-L487

This is bad for accessibility, prevents people from seeing where the link goes before they click on it, prevents people from right clicking on it, middle mouse clicking on it, etc.

Other instances of onclick handlers in the settings page should similarily be re-evaluated to determine whether they can be normal `<a>` elements with an `href`.

**Browser**
Chromium on Linux

*Note: I unsubscribed from this issue, so if you want a reply, make sure to @ me*

**Comment by veloce-vasta** [comment]
I'll work on this

**Comment by veloce-vasta** [comment]
@rgantzos Why is the h3 on line 466?

**Comment by veloce-vasta** [comment]
> @rgantzos Why is the h3 on line 466?
