### ISSUE TITLE
You are not quite following the MIT license properly

### ISSUE THREAD

**Issue by GarboMuffin** [STForScratch/ScratchTools#366]
See this file:

https://github.com/STForScratch/ScratchTools/blob/main/licenses/mit.txt

Specifically see this line:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

While you have included the permission notice, you have not included the copyright notice. It is my understanding that this file is in reference to some code imported from https://github.com/forkphorus/cat-plus/, which has a copyright notice:

> Copyright (c) 2019 Thomas Weber

I do not intend to enforce the license on this code, but since you're trying to follow the license, I figure you should do so completely

**Comment by MaterArc** [comment]
Yeah, just did a little more research. This is correct, totally agree. I've fixed this issue here: https://github.com/STForScratch/ScratchTools/pull/374
