### ISSUE TITLE
New Extensions

### ISSUE THREAD

**Issue by CoolWWebsites** [STForScratch/ScratchTools#370]
**Smooth Fixes.**
"Smooth Fixes"
**Additional context**
nothing

**Comment by rgantzos** [comment]
Could you please elaborate?

**Comment by StioStudio** [comment]
> **Smooth Fixes.** "Smooth Fixes" **Additional context** nothing

What do you mean with "Smooth Fixes"?



> Could you please elaborate?

While I am here. Do STE do custom blocks and extensions?

**Comment by rgantzos** [comment]
> While I am here. Do STE do custom blocks and extensions?
Not at the moment, no.
