### ISSUE TITLE
Switching to "Scratch Tools"

### ISSUE THREAD

**Issue by rgantzos** [STForScratch/ScratchTools#372]
Currently, the extension name and branding is "ScratchTools". However, the fact that the single word "Scratch" isn't in the name by itself lowers our listing in the Chrome Web Store extension search, making it harder to find ScratchTools by searching for "Scratch".

There are a few solutions:
- Switch the name to "Scratch Tools", although this may lower how recognizable we are, and doesn't have the same style as a one-word name.
- Add a tagline to the end of the long name (not the short name) which displays in the web store, it just can't be too long to take up too much space and squish elements on the extensions page.

There isn't really much else we can do.

**Comment by MaterArc** [comment]
Discussed.
