### ISSUE TITLE
Unlisted Project (Unlist/Private):  make a project private without having to go into the original project 

### ISSUE THREAD

**Issue by ksdavidc** [STForScratch/ScratchTools#379]
# Summary
I suggest providing a way of listing or privatizing without having to go into the original project. Or put another way, allow project sharers a way to better manage the projects they have unlisted.

2 ideas for how:
1. Mark the projects in the "My stuff" page, such as with symbol or (preferably) buttons that allow them to be made private.
2. Provide an interface within scratchtools to do the same.

# General Discussion
Generating these links is a great feature, and I really appreciate it. It is helping me look at student projects without having them share or copy them. 

It appears the design is that:
- Once it generates a link, it appears that one has to return to the original project to remove the link. (is that true?)
- It is not possible to get the link or make it private from within Turbowarp (other than copying the url) or outside the project in the Scratch interface, or in the Scratchblocks interface (true?)

My concern is about losing track of which projects have been unlisted so that I can relist them. 

The current system makes sense, but it would be useful to be able to make a project private/listed without having to go into the original project. I understand it would have to be done from within the original account, but if I have several links, or an old link, it is easy to lose track of which are unlisted. 

For example, would it be possible to mark/link/button the projects in the "My stuff" page that have been unlisted? Or provide a button/link or some other interface (within scratchtools?) to list/privatize them?

The terminology (unlist <-> make private) is a little awkward for me - (what list are we talking about? Why unlist? isn't the project private if is not shared?) as the various metaphors (list/privacy/sharing) overlap in meaning, but should be distinct. When a project is in the state listed it is private, and if it is in the state unlisted it would be public, which for me is counterintuitive. I think it would be easier to grasp if only one metaphor were used.  There are many possible metaphors, and the best one for me that I could think of was activate scratchtools snapshot/ inactivate scratchtools snapshot. This tries to reflect the fact that once the snapshot is activated, then if it is inactivated, that snapshot is useless. Meanwhile reactivating it generates a new snapshot and makes the old one disappear, i.e. with only zero or one snapshot being active for any project at any time. At any rate, I did find list/private confusing.

**Comment by ksdavidc** [comment]
i realized something else I would like: a way to see the link for unlisted projects within the project itself AFTER is has been unlisted and the popup has been closed (other than listing and unlisting again, which breaks the old link).

**Comment by rgantzos** [comment]
@ksdavidc Yes, you currently do have to go back into the project to remove the link. We don't control Turbowarp, but I like the idea of adding a symbol next to projects that are unlisted and a way to make them unlisted or copy the link via the My Stuff page.

As for the terminology behind the word unlisted, it's based on YouTube in a way. Unlisted means that it isn't listed on your profile, in the search, or in studios, but others can still access it with a direct link. Private means only you can view it. However, something similar to Google's sharing system might be better in this situation.

**Comment by ksdavidc** [comment]
I am glad you are open to the suggestion. Unlisted/private makes more sense now, I just didn't land on that interpretation right away. (Still I think one metaphor is better...) 

Your plugin is a clever idea, that fixes a big problem for me as a teacher. I've want to be able to share projects with/from students without having to share them globally or get into downloads and sending files. Being able to turn it on and off seems like magic to me!

**Comment by rgantzos** [comment]
@ksdavidc This has been added into v2.27.0, which will be released this coming week. Some of the changes to the feature include better morals for displaying the unlisted link, a way to view the link from the project page without making the project private and unlisted again, and it will also add a star next to unlisted projects on the My Stuff page.

**Comment by ksdavidc** [comment]
absolutely awesome. Better morals, and modals, too, I hope. Looking forward to it!!

**Comment by rgantzos** [comment]
> absolutely awesome. Better morals, and modals, too, I hope. Looking forward to it!!

Lol thanks, weird autocorrect.

**Comment by ksdavidc** [comment]
NIce. working great...except for the new bug ;-) . But I like how it turned out. Thank you.
