### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Daniel4-Scratch** [STForScratch/ScratchTools#421]
- [x] Dark mode CSS
- [x] Dark mode JS
- [x] Toggle option in settings
- [x] Toggle option in onboarding

Giving this priority tag because heaps of users have requested dark mode
I'll work on it soon as possible

**Comment by rgantzos** [comment]
@Daniel4-Scratch Are you currently working on this? If not, I think it should be added to the 2.28 milestone.

**Comment by Daniel4-Scratch** [comment]
@rgantzos im just starting now

**Comment by rgantzos** [comment]
I think this should wait until v2.28.0. I just switched the milestone.
