### ISSUE TITLE
nicknames not working throws error

### ISSUE THREAD

**Issue by ksdavidc** [STForScratch/ScratchTools#422]
### Describe the bug. What is going wrong?

nicknames is not working and throwing error in console. run with all other extensions off, and few chrome extensions as well.

```
DevTools failed to load source map: Could not load content for chrome-extension://apbbkgiadnodlonfadecfkpjkfakklnf/js/browser-polyfill.min.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
main.js:4 ScratchTools API Created
logging.js:18 ScratchTools Unable to load Virtual Machine.
logging.js:18 ScratchTools Unable to load Blockly.
VM6859:1 Uncaught SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at nicknames.js:1:24
(anonymous) @ nicknames.js:1
```

### What is causing the bug?

this line: `const nicknames = JSON.parse(localStorage.getItem("scratchtools-nicknames") || {});`

**Comment by rgantzos** [comment]
@ksdavidc what version are you using?

**Comment by ksdavidc** [comment]
the one that just came out 2.26.0. was hoping unlisted would be there, but not there yet, I guess..

**Comment by rgantzos** [comment]
> the one that just came out 2.26.0. was hoping unlisted would be there, but not there yet, I guess..

Unlisted should be there…

**Comment by ksdavidc** [comment]
I mean it is there, but the changes we talked about are not there yet (I don't see any change), scheduled for 2.27 you said.

**Comment by rgantzos** [comment]
> I mean it is there, but the changes we talked about are not there yet (I don't see any change), scheduled for 2.27 you said.

Oh, yeah. Those ones won’t be available until 2.27, but feel free to download the beta if you want to use them. They work well. They’ll probably release today or tomorrow, and then Chrome will finish reviewing them later.

**Comment by ksdavidc** [comment]
(sorry, unlisted was off topic.) Thanks. Just to be clear, this issue though is just with nicknames...is that also due for 2.27 because the release page for 2.26 says: "Fix nicknames feature." and I see the PR https://github.com/STForScratch/ScratchTools/pull/398#issue-1676981793

**Comment by ksdavidc** [comment]
Ok, I see you did do that. Thanks, sorry for the confusion. carry on...
