### ISSUE TITLE
no user select in onboarding

### ISSUE THREAD

**Issue by callumjt** [STForScratch/ScratchTools#427]
### How does the feature work?

its not a new feature

### What situations would make this helpful?

make it look nicer

### Anything else?

no

**Comment by callumjt** [comment]
> @callumjt What user select?

So you can't select the text

**Comment by rgantzos** [comment]
> > @callumjt What user select?
> 
> So you can't select the text

I’m not sure if this is needed… there’s nothing wrong with being able to select the text
