### ISSUE TITLE
`downloadProjectId()` throws 403

### ISSUE THREAD

**Issue by Samq64** [STForScratch/ScratchTools#438]
### Describe the bug. What is going wrong?

The `downloadProjectId()` function throws a 403 Forbidden error code.

### What is causing the bug?

Scratch updated their API, so now projects can't be fetched without a project token

**Comment by callumjt** [comment]
Oh true

**Comment by callumjt** [comment]
What addon uses downloadProjectId()?

**Comment by rgantzos** [comment]
> downloadProjectId

One that we should probably remove.

**Comment by rgantzos** [comment]
This was resolved with #439
