### ISSUE TITLE
Userscript matching

### ISSUE THREAD

**Issue by Samq64** [STForScratch/ScratchTools#444]
### How does the feature work?

Userscript/userstyle matching should be added at least as an option to `features.json` and `data.json` similar to Scratch Addons, so they only run on the specified pages

### What situations would make this helpful?

So almost all those console errors can be fixed without surrounding every userscript with an `if(location.pathname.match(regex-here))`

**Comment by callumjt** [comment]
I honestly agree, wouldn't this also improve performance in some cases? Or am I just being stupid
