### ISSUE TITLE
Rewrite settings page HTML/CSS

### ISSUE THREAD

**Issue by GarboMuffin** [STForScratch/ScratchTools#462]
### Describe the bug. What is going wrong?

![image](https://github.com/STForScratch/ScratchTools/assets/33787854/18daf947-838f-4545-bd49-bd63afef4039)

 - each addon settings widget should not have a scroll bar for no reason
 - the page itself *should* have a scroll bar but it does not

### What is causing the bug?

n/a

### Anything else?

I unsubscribed from this issue, so @ me if you want more details

**Comment by rgantzos** [comment]
We've been trying to redesign the settings page to be more efficient with space. @Daniel4-Scratch any ideas?

**Comment by Daniel4-Scratch** [comment]
The settings page was made poorly, i reckon we should start the settings page from scratch again.

**Comment by rgantzos** [comment]
> The settings page was made poorly, i reckon we should start the settings page from scratch again.

Alright, so here's what we should work on:
- Moving the CSS to a separate file
- Deciding how features will be displayed
- Deciding what additional elements should be kept, and where they should go

**Comment by callumjt** [comment]
> The settings page was made poorly, i reckon we should start the settings page from scratch again.

I honestly agree

**Comment by rgantzos** [comment]
I'm removing this from the v2.29.0 milestone since there have been pull requests merged to fix a few of these already. However, I still think that the settings page should be redesigned at some point.
