### ISSUE TITLE
Colored editor comments does excessive work when adding comments

### ISSUE THREAD

**Issue by GarboMuffin** [STForScratch/ScratchTools#464]
### Describe the bug. What is going wrong?

The addon is doing *something* for 200ms every time you add a comment

![image](https://github.com/STForScratch/ScratchTools/assets/33787854/6ac7b509-2a57-413c-a9e1-761dba25e8da)

It does not need to do that

### What is causing the bug?

Colored editor comments

### Anything else?

I unsubscribed from this issue, so @ me if you want more details

**Comment by rgantzos** [comment]
It doesn't seem to use the waitForElements API, which would speed it up significantly.
