### ISSUE TITLE
Add a feedback button to settings page

### ISSUE THREAD

**Issue by rgantzos** [STForScratch/ScratchTools#483]
Lots of people don't know how to leave feedback, so they go to Scratch. Then, you can't give them the URL to the feedback page.

It's a good idea to add a button to the settings page, maybe under "Additional settings".

**Comment by MaterArc** [comment]
Interesting. Yeah, this makes sense. It's really hard otherwise to explain to people where to go, or rather the directions to get there. Full support for this.

**Comment by rgantzos** [comment]
I'm thinking something in-extension, and, using the new verification system that was implemented, maybe it could include the username when it's submitted?
