### ISSUE TITLE
Bug Addon: Plain Background

### ISSUE THREAD

**Issue by GuiAvelin0** [STForScratch/ScratchTools#493]
I've found a bug in this addon that if you scroll to a thing that isn't a block, it doesn't scroll, only lets scroll in blocks.
Example: my mouse is not in a block, doesn't scroll but in a block it let scroll. this is bad for me

**Comment by MaterArc** [comment]
Wait, what do you mean by a thing that isn't a block? The feature only applies to the editor, so I would assume the only thing in the editor workspace is blocks? Sorry, I just need a clarification....

**Comment by GuiAvelin0** [comment]
Comments are in the editor and i can't scroll them, and i can't use my right mouse button too (i've found that now) i've tried that on my laptop, please try it.

**Comment by MaterArc** [comment]
It all works for me of Macbook. I will test this further with a different device and possibly browser when I get the chance.

**Comment by GuiAvelin0** [comment]
oh. maybe i'm on windows that caused the bug

**Comment by MaterArc** [comment]
This seems to be fixed with #883 as well
