### ISSUE TITLE
I would like to import settings.

### ISSUE THREAD

**Issue by JasperRedI** [STForScratch/ScratchTools#495]
So, I just installed a new browser, and I want to use ScratchTools on it. I don't want to go through the trouble of trying to copy over all of the settings I had customized like I had to do for Youtube Redux. So, I need a way to import settings. So, if there's already a way to do that, please inform me and tell me how. If there isn't a way, please add one. Thanks!

~ Jasper

**Comment by MaterArc** [comment]
There is already a way to copy the feature code in additional settings for ScratchTools, but I'm not sure if there is a way to import it that I know know of just by using the code. If not, it seems like a great idea that could be fairly simple feature to code! Thanks for opening an issue, rgantzos will probobly comment here soon...

**Comment by rgantzos** [comment]
I will work on a way to import settings.

**Comment by rgantzos** [comment]
This is part of #241
