### ISSUE TITLE
Asking to not give credit in translations.

### ISSUE THREAD

**Issue by GuiAvelin0** [STForScratch/ScratchTools#565]
Hi i've helped ScratchTools from translation and could to not give credit to me? i care a little bit more of privacy, my username on app.transifex.com is GuiAvelino.

**Comment by rgantzos** [comment]
I don't think you're on the credits page...

**Comment by callumjt** [comment]
I think he means on transifex but I don't think that's public is it?

**Comment by GuiAvelin0** [comment]
yeah.
