### ISSUE TITLE
My stuff has 2 trash

### ISSUE THREAD

**Issue by kokofixcomputers** [STForScratch/ScratchTools#608]
### Describe the bug. What is going wrong?

In the mystuff page there is 2 trash

Screenshots:

with ScratchAddons:

<img width="252" alt="Screen Shot 2023-08-05 at 8 35 04 AM" src="https://github.com/STForScratch/ScratchTools/assets/113046561/f79ed401-1285-4ebe-85a7-228b02301806">

without ScratchAddons:

<img width="252" alt="Screen Shot 2023-08-05 at 8 37 41 AM" src="https://github.com/STForScratch/ScratchTools/assets/113046561/12d39cc2-796a-41b6-9c87-2513eb62cf35">

### What is causing the bug?

In the mystuff page

**Comment by StioStudio** [comment]
Can you send the Feature Codes?

**Comment by kokofixcomputers** [comment]
What do you mean feature codes? 

This is the json:


[scratchtools-settings.json.zip](https://github.com/STForScratch/ScratchTools/files/12267779/scratchtools-settings.json.zip)

**Comment by callumjt** [comment]
I'm pretty sure this has been reported in the discord before, what version are you on?

**Comment by MaterArc** [comment]
> 

Yeah, you’re correct. It has been reported multiple times in the last few months
