### ISSUE TITLE
ScratchTools `default-to-local` not working with Scratch Addons `swap-local-global`

### ISSUE THREAD

**Issue by rgantzos** [STForScratch/ScratchTools#668]
### Describe the bug. What is going wrong?

From feedback:

> The ScratchTools "Default to Local Variables" addon seems to have a conflict with the Scratch Addons "Switch variables between "For all sprites" and "For this sprite only"". The conflict appears when renaming a global variable. The global variable is redefined to be local. I would expect only set NEW variables to be set to local, not the redefining already defined variables.
>
> Of course I don't which addons, or if both, is responsible, so I am alerting both developers.

### What is causing the bug?

In the editor, if you open the rename modal with both features/addons enabled, it will automatically select Default to Local.

**Comment by ksdavidc** [comment]
It just occured to me that rather merely than having a default, it might be nice to have the option to remember the last setting. For example, if I am working with clones, I want to be using local default, but if I am then working on something more global, say score or health, I want to be in global mode.
