### ISSUE TITLE
plain background, and menu button suggestions

### ISSUE THREAD

**Issue by ksdavidc** [STForScratch/ScratchTools#67]
**Please describe your idea.**
A clear and concise description of what the feature would do.

the plain background plugin overrides other colors I may have been set via other plugins. That is to say, it defaults to a white background. Would it be possible to choose the color?

I think the popup on the menu item should probably include somewhere a link to your project page (https://tools.scratchstatus.org/) or the docs, or the github page. For example, when I wanted to post this suggestion I had to take several steps to find this page.

Plus, it would be nice if it were searchable, e.g. if I want to change a particular setting, finding it can be troublesome.
 
**Describe how the idea would be helpful**
A clear and concise description of how the feature would be helpful to users.
self-evident

**Additional context**

**Comment by rgantzosonscratch** [comment]
1. We’re working on a fix for the plain background one.
2. We will be adding links to the FAQ and main site.
3. We are also working on making it searchable and adding features. We may add a separate settings page.

**Comment by rgantzosonscratch** [comment]
We've added a nice search too :)

**Comment by ksdavidc** [comment]
This is definitely improved, but I still don't see a link to the FAQ and main site, or at least a way to leave feedback. Am I missing something? I see links to individual contributors...

**Comment by rgantzosonscratch** [comment]
> This is definitely improved, but I still don't see a link to the FAQ and main site, or at least a way to leave feedback. Am I missing something? I see links to individual contributors...

Our document site is a work in progress. [Here's a work-in-progress version of our FAQ](https://docs.scratchstatus.org/#/?id=faq). You can leave feedback [here](https://tools.scratchstatus.org/feedback/). Sorry, the feedback page requires verification due to spammers.

**Comment by rgantzosonscratch** [comment]
> **Please describe your idea.** A clear and concise description of what the feature would do.
> 
> the plain background plugin overrides other colors I may have been set via other plugins. That is to say, it defaults to a white background. Would it be possible to choose the color?
> 
> I think the popup on the menu item should probably include somewhere a link to your project page (https://tools.scratchstatus.org/) or the docs, or the github page. For example, when I wanted to post this suggestion I had to take several steps to find this page.
> 
> Plus, it would be nice if it were searchable, e.g. if I want to change a particular setting, finding it can be troublesome.
> 
> **Describe how the idea would be helpful** A clear and concise description of how the feature would be helpful to users. self-evident
> 
> **Additional context** Add any other context or screenshots about the feature request here.

Also, ScratchTools' dark mode is compatible with plain background.
