### ISSUE TITLE
ScratchTools `live-character-counts` not working with Scratch Addons `project-notes-tabs`

### ISSUE THREAD

**Issue by rgantzos** [STForScratch/ScratchTools#677]
(Thanks to Jazza for reporting)

![Image](https://user-images.githubusercontent.com/86856959/263875203-3ae65c55-f649-4dee-9a63-2f3b76bae733.png)

When using ScratchTools and Scratch Addons, the font size is incorrect within the Scratch Addons project notes tabs.

**Comment by medlans** [comment]
In the Scratch Addons version (given in the issue on the other repository), I'm assuming you mean 35, not 34.

**Comment by rgantzos** [comment]
> In the Scratch Addons version (given in the issue on the other repository), I'm assuming you mean 35, not 34.

no, 34.

**Comment by medlans** [comment]
> > In the Scratch Addons version (given in the issue on the other repository), I'm assuming you mean 35, not 34.
> 
> no, 34.

Oh, I thought you'd use the latest version of it XD. But I can replicate with 1.34.1 anyway so..

**Comment by Samq64** [comment]
This will be fixed by https://github.com/ScratchAddons/ScratchAddons/pull/6607.
