### ISSUE TITLE
2.0 editor (ScratchTools) isn't compatible with collapsing sprite properties (Scratch Addons)

### ISSUE THREAD

**Issue by medlans** [STForScratch/ScratchTools#678]
### Describe the bug. What is going wrong?

If you have these 2 enabled, then you can't view the sprite properties, and the info button disappears when you try to click on it. 
OS: Mac OS Big Sur (11.3)
Browser: Chrome 116
Scratch Addons version: 1.34.1
Scratch Tools:
Version: 3.1.2
Features enabled: 5
Language: en-US

### What is causing the bug?

1. Enable 2.0 editor on ScratchTools and the collapsing sprite properties addon on Scratch Addons.
2. Go to the Scratch editor.
3. Try to view the sprite properties by clicking the info button.
4. See the error.

**Comment by medlans** [comment]
Does anyone know if this is still happening?

**Comment by MaterArc** [comment]
Enabling those two at the same time seems to work fine for me now

> Does anyone know if this is still happening?
