### ISSUE TITLE
At first, title of hid tags and display tags plugins are confusing

### ISSUE THREAD

**Issue by ksdavidc** [STForScratch/ScratchTools#734]
### Describe the bug. What is going wrong?

The titles of these two plugins seem contradictory. It led me to think, what would happen if I enabled both of them? Well, after I realized the second one is about displaying a separate text box below with the tags, I expected that the tags in the instructions/Notes would disappear, but they would still appear in the Tags text box. This is not what happened.  Or at least I think so, because to be honest the behavior was quite inconsistent and I had to reload the projects several times to see the tags properly as links. Depending on how/when I pressed Preview the tags box would appear below or above the notes and credits, or even not appear at all. 

This all started because I was trying out the ScratchAddons Preview tool, and there could be a conflict there, though even with that off, things weren't right. 

I am sorry I can't give a clearer description, but i am done fiddling with it. This is just FYI, and hopefully others will have more meaningful input.

Hide Project Tags
Hides all linked tags in the Instructions/Notes and Credits of projects.

Display Project Tags
Lists all of the tags used in the project description right below the project notes and credits.

### What is causing the bug?

no idea

**Comment by rgantzos** [comment]
I just fixed the bugs. However, the "Display Project Tags" should be named something like "Separate Project Tags" in the future. This can't be added to v3.4.0 for localization reasons, but it can be added to v3.5.0.
