### ISSUE TITLE
unable to right click custom blocks to get menu (edit, add comment)

### ISSUE THREAD

**Issue by ksdavidc** [STForScratch/ScratchTools#750]
### Describe the bug. What is going wrong?

with the extension off, one can edit and add comments to myblock definitions by right clicking.
<img width="311" alt="Screen Shot 2023-11-11 at 7 57 16 AM" src="https://github.com/STForScratch/ScratchTools/assets/62230004/6ec8c408-b666-4e7b-9480-396fe181e499">

turning on the extension blocks this. A different context menu opens and one can still add comments to the editor, but not the block itself. Once can still edit by right clicking in the block pallette.
<img width="286" alt="Screen Shot 2023-11-11 at 7 57 39 AM" src="https://github.com/STForScratch/ScratchTools/assets/62230004/dc5e9a6b-6101-47a3-a337-606cbb5b8664">

### What is causing the bug?

voodoo?

### Anything else?

To be clear, this happens even if I load the extension WITH NO EXTENSIONS ACTIVE.

**Comment by StioStudio** [comment]
Oh that is neat

**Comment by medlans** [comment]
Can replicate after deleting a custom block and then undoing, it doesn't happen if "undo" and "redo" don't show up for me. Also, after deleting it and then undoing, the context menu isn't purple anymore even though I have context menu colors on.
![testingblock](https://github.com/STForScratch/ScratchTools/assets/124630024/fe3dfb75-7deb-4f91-a629-4b6267e9d0b2)
![comparisoncontext](https://github.com/STForScratch/ScratchTools/assets/124630024/49a65099-00a0-4ceb-b426-7dd8f91be9e7)

**Comment by ksdavidc** [comment]
Oh that is neat

**Comment by ksdavidc** [comment]
Was mentioned in discord here, with further information, including log report. https://discord.com/channels/945340853189247016/1198301461495427154
