### ISSUE TITLE
Compact navbar incompatible with SA compact user dropdown (race condition probably)

### ISSUE THREAD

**Issue by OneShot-Niko** [STForScratch/ScratchTools#751]
### Describe the bug. What is going wrong?

Via ScratchTools' Compact Navbar and ScratchAddons' Customizable Navbar ("Compact user dropdown" in specific) enabled, the user dropdown just displays a blank and is unusable. <sub>(Though I bet this isn't really fixable I'd rather report it just incase)</sub>

### What is causing the bug?

1. Enable customizable navigation bar & compact user dropdown in ScratchAddons
2. Enable compact navbar in ScratchTools
3. Attempt to look at your profile dropdown (when both userscripts load) - It'll be only a blank and is unusable.
Screenshot:
![bug](https://github.com/STForScratch/ScratchTools/assets/150537842/a5aa9e34-8859-4a43-bb57-0d00e3082a8e)

### Anything else?

ScratchAddons v1.35.1
ScratchTools v3.4.0
Done on Vivaldi (uses the chrome version) though I think this basically goes for the browsers that both extensions support. (Disincluding Firefox since the ff version of the extension is heavy outdated - [It does duplicate the username in the profile dropdown](https://github.com/STForScratch/ScratchTools/assets/150537842/a30dd52e-4974-4e43-9949-3d057c4c026e), however has no other affect from what I can tell, though not really change-able due to currently unsupported APIs)

**Comment by callumjt** [comment]
Well uhh that shouldn’t happen and I don’t see why it is happening

**Comment by rgantzos** [comment]
I'm closing this because there doesn't seem to be any reason to have both enabled at the same time.
