### ISSUE TITLE
scrollbar gets layered by navbar in fullscreen settings

### ISSUE THREAD

**Issue by ghost** [STForScratch/ScratchTools#755]
### Describe the bug. What is going wrong?

Going into the fullscreen settings page, the scroll bar is layered over by the navbar.

### What is causing the bug?

Couldn't find a fix via inspect and can't find the addons page in the repo.
EDIT: If I do find anything I'll probably try either PR'ing (if I find a fix) or just mentioning it.

### Anything else?

![vivaldi](https://github.com/STForScratch/ScratchTools/assets/150537842/a97629a1-cb09-4251-9dd5-2ce269a6929f) (Vivaldi / Chromium)
![msedge](https://github.com/STForScratch/ScratchTools/assets/150537842/e7f3981f-b20b-4013-bb26-3aa82d3f5fc3) (Edge)
No firefox example because it's outdated there - No real point in trying since that's a really old version.

**Comment by callumjt** [comment]
How the O.o

**Comment by StioStudio** [comment]
I have fixed it all ready :) It should come next update
