### ISSUE TITLE
Editor Darkmode skips a few icons

### ISSUE THREAD

**Issue by OneShot-Niko** [STForScratch/ScratchTools#756]
### Describe the bug. What is going wrong?

Plain Background overrides the color schemes of the entire editor, though only the code area is dotted, so that should be the only thing that is getting changed (unless the other icons are dotted as well, though I can't tell).
### What is causing the bug?

Disabling either one of the addons fixes this, unsure of the core cause.

Couldn't find a dupe but will close if needed.

### Anything else?

As an interesting note, if you have SA's editor dark mode enabled as well, then the editor's code plane will start flashing, or won't flash.

And having both of these on will randomly default back the colors of buttons (eg. full screen)
Example of this happening on Vivaldi, I circled the 2 buttons that got affected here.
![vivaldi](https://github.com/STForScratch/ScratchTools/assets/150537842/e2cae567-8587-4a2c-8efe-417dd02d2000)

**Comment by MaterArc** [comment]
@OneShot-Niko This seems to be a problem with the Editor Dark Mode feature itself and not the fact that they the two features are being enabled at the same time. I've tested it, and it seems like even when the plain background feature is disabled and the editor dark mode one is enabled, the colors still take the default scratch purple (#855CD6).

**Comment by OneShot-Niko** [comment]
> @OneShot-Niko This seems to be a problem with the Editor Dark Mode feature itself and not the fact that they the two features are being enabled at the same time. I've tested it, and it seems like even when the plain background feature is disabled and the editor dark mode one is enabled, the colors still take the default scratch purple (#855CD6).

Ah - I'll retitle then
Couldn't get this to happen last I tried with plain background off though which is odd
