### ISSUE TITLE
Costume Editor glitch

### ISSUE THREAD

**Issue by Floog98** [STForScratch/ScratchTools#808]
### Describe the bug. What is going wrong?

When i switch between vector and bitmap costumes the gui for them goes gray and to fix it i have to switch to a different tab like code then switch back to costumes tab. 

### What is causing the bug?

it happens in the costumes editor when scratch tools is enabled 

Uploading Recording 2024-03-16 115111.mp4…

but to let you know i'm on chrome windows 11

**Comment by MaterArc** [comment]
Is it possible you could send a video of the problem occuring and your ScratchTools feature code (JSON)?

_To get your feature code:_ 
1. Open up ScratchTools extension
2. Click the settings icon to bring you into our full-screen settings
3. In the bottom-left hand corner, you should see an additional settings button, click that
4. Then click the button that says "export settings" 

The file should get downloaded to your computer, and it would be really great if you could upload it here. It just makes our lives easier as it makes pinpointed the exact feature that is causing the bug that much smoother.

**Comment by Floog98** [comment]
okay

https://github.com/STForScratch/ScratchTools/assets/160561150/7fede2c9-c6fb-438b-91a6-bf1a51dce0d4

[scratchtools-settings.json](https://github.com/STForScratch/ScratchTools/files/14625685/scratchtools-settings.json)

**Comment by rgantzos** [comment]
This was fixed sometime back and will be released in v4.0.0.
