### ISSUE TITLE
I want to join

### ISSUE THREAD

**Issue by jayz3314** [STForScratch/ScratchTools#819]
Hello, I would like to join scratchtools as any role you have available.
[My scratch account](https://scratch.mit.edu/users/jayz33)
`while true:
          code`

**Comment by rgantzos** [comment]
@jayz3314 I'm happy to hear that you're interested in contributing! Do you happen to have a Discord account? If not, that's fine. A lot of the work on ScratchTools happens within a Discord server so an account would be convenient, but not required.

**Comment by jayz3314** [comment]
> @jayz3314 I'm happy to hear that you're interested in contributing! Do you happen to have a Discord account? If not, that's fine. A lot of the work on ScratchTools happens within a Discord server so an account would be convenient, but not required.
I'm really sorry, but I don't have one. Also, which role am I?
