### ISSUE TITLE
Add littlest pet shop feature

### ISSUE THREAD

**Issue by CrazyGamingworks** [STForScratch/ScratchTools#89]
nvm

**Comment by CrazyGamingworks** [comment]
I think it would be a good feature

**Comment by rgantzosonscratch** [comment]
I'm sorry, I'm unaware of what you mean by this.

**Comment by CrazyGamingworks** [comment]
> I'm sorry, I'm unaware of what you mean by this.

Wrong repository apologies

**Comment by CrazyGamingworks** [comment]
Deleted
