### ISSUE TITLE
Project title above stage + dark mode on Scratch Addons makes title difficult to see

### ISSUE THREAD

**Issue by medlans** [STForScratch/ScratchTools#977]
### Describe the bug. What is going wrong?

1. Enable "Editor dark mode and customizable block colors" on Scratch Addons, and choose dark colors.
2. Enable project title above stage on ScratchTools
3. Go to the editor
4. See bug

### What is causing the bug?

I'm not sure where exactly, though it might not be changing color based on dark mode at all.

### Anything else?

This might be slightly annoying, as there's only one editor dark mode available on ScratchTools. Also, a similar issue seems to happen when highlighting the title with the ScratchTools editor dark mode with project title above stage also on (the editor dark mode looks to be broken on ScratchTools or looks very weird, as only the block palette and the scripts area are dark mode and some inputs, at least when I enable it by itself, but that's likely a different thing)

**Comment by MaterArc** [comment]
> ### Describe the bug. What is going wrong?
> 1. Enable "Editor dark mode and customizable block colors" on Scratch Addons, and choose dark colors.
> 2. Enable project title above stage on ScratchTools
> 3. Go to the editor
> 4. See bug
> 
> ### What is causing the bug?
> I'm not sure where exactly, though it might not be changing color based on dark mode at all.
> 
> ### Anything else?
> This might be slightly annoying, as there's only one editor dark mode available on ScratchTools. Also, a similar issue seems to happen when highlighting the title with the ScratchTools editor dark mode with project title above stage also on (the editor dark mode looks to be broken on ScratchTools or looks very weird, as only the block palette and the scripts area are dark mode and some inputs, at least when I enable it by itself, but that's likely a different thing)

That's weird, when I have enable the ones outlined in the steps you provided, everything seems to be working fine. 
<img width="1436" alt="Screenshot 2024-12-28 at 11 21 20 AM" src="https://github.com/user-attachments/assets/3c96a435-3d37-4292-be78-72f29b8df64c" />

**Comment by MaterArc** [comment]
Could you maybe provide a screenshot on your end?

**Comment by medlans** [comment]
> > ### Describe the bug. What is going wrong?
> > 
> > 1. Enable "Editor dark mode and customizable block colors" on Scratch Addons, and choose dark colors.
> > 2. Enable project title above stage on ScratchTools
> > 3. Go to the editor
> > 4. See bug
> > 
> > ### What is causing the bug?
> > I'm not sure where exactly, though it might not be changing color based on dark mode at all.
> > ### Anything else?
> > This might be slightly annoying, as there's only one editor dark mode available on ScratchTools. Also, a similar issue seems to happen when highlighting the title with the ScratchTools editor dark mode with project title above stage also on (the editor dark mode looks to be broken on ScratchTools or looks very weird, as only the block palette and the scripts area are dark mode and some inputs, at least when I enable it by itself, but that's likely a different thing)
> 
> That's weird, when I have enable the ones outlined in the steps you provided, everything seems to be working fine. <img alt="Screenshot 2024-12-28 at 11 21 20 AM" width="1436" src="https://private-user-images.githubusercontent.com/105017592/399095910-3c96a435-3d37-4292-be78-72f29b8df64c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0MDkyNTcsIm5iZiI6MTczNTQwODk1NywicGF0aCI6Ii8xMDUwMTc1OTIvMzk5MDk1OTEwLTNjOTZhNDM1LTNkMzctNDI5Mi1iZTc4LTcyZjI5YjhkZjY0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQxODAyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2RlMWI2NmNkYjc5ZjdlNmI0ZjA3MTE4YzRkODZjZDQ5YjAzZmMxNGMzODc5NzFlYTIzNzcwYzFmNDQ0Yzk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pnAhkjBCHVa61T2xHZAEYW-y78JuBE_GOx6SuOWC2_M">

Yea I meant the fact that it was dark grey on black there. Certain settings make it harder to see.

**Comment by medlans** [comment]
![DarkModeEditor](https://github.com/user-attachments/assets/fb3770ef-7631-4245-8279-6c1334bdecba)
![DarkModeST](https://github.com/user-attachments/assets/dcc13684-a7d2-4e28-af39-3681d4264add)
![DarkModeST2](https://github.com/user-attachments/assets/f5f5b016-a6be-4276-bec6-114cccd3d106)

This is what it looked like for me

**Comment by MaterArc** [comment]
@medlans This is anyways fixed by the PR that I made to fix the Editor Dark Mode feature, it now looks like this:
<img width="1440" alt="Screenshot 2024-12-28 at 1 28 39 PM" src="https://github.com/user-attachments/assets/ec56a9aa-b4e2-49a1-b6a0-76645eab0b36" />
