### ISSUE TITLE
Quotes on the forums append "Open in Ocular" to usernames

### ISSUE THREAD

**Issue by jeffalo** [STForScratch/ScratchTools#99]
Noticed this recently, and tracked it down to your extension. It looks like whenever a user of your extension quotes a post on the forums, it appends "Open in Ocular" to usernames in the quotes.

https://ocular-rewritten.jeffalo.net/search?q=ocular&sort=newest

![image](https://user-images.githubusercontent.com/40470736/180404932-e1ecc3bb-acc6-4bad-8071-711b2ca6a4bc.png)

https://github.com/rgantzosonscratch/ScratchTools/blob/main/features/ocular-link.js

Scratch's quote button just grabs the username from `.username`'s text.

```js
function copy_paste(id) {
    var post = $('#' + id);
    var username = post.find(".username").text();
    $.ajax('/discuss/post/' + id.substr(1) + '/source/').done(function (data) {
        paste('[quote=' + username + ']' + data + '[/quote]\n');
    });
}
```

**Comment by rgantzosonscratch** [comment]
Thank you so much for pointing this out, I will fix it now!

**Comment by rgantzosonscratch** [comment]
> it hasn't been fixed? https://ocular.jeffalo.net/search?q=ocular&sort=newest

I will look into this.
